---
# INFORMATION SUR LE PROJET
site_name: BASE DOCUMENTAIRE
site_description: >-
  Retrouvez ici toute la documentation produite par le service Information Géographique et Observatoire
  de Vienne Condrieu Agglomération
site_author: Fabien ALLAMANCHE
# site_url: https://doc-igeo.vienne-condrieu-agglomeration.fr/
copyright: 2024 &copy; Vienne Condrieu Agglomération

# DÉPÔT
repo_name: vca/base-documentaire
repo_url: https://github.com/vienne-condrieu-agglomeration/igeo
edit_uri: edit/master/docs

# STRUCTURE DE DOSSIER PERSONNALISÉE
docs_dir: ./docs

# THÈME
theme:
  name: material
  language: fr
  custom_dir: theme
  logo: assets/images/logo/vca-logo-white.png
  favicon: assets/images/logo/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
  font:
    text: Encode Sans
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections # prevents collapsible sections
    - navigation.indexes # section index pages
    - navigation.expand #expands sections by default
    - navigation.tabs # section tabs along the top
    - navigation.top
    - navigation.footer
    - toc.follow
    # - toc.integrate # moves toc to the left
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide

# PERSONNALISATION  
extra:
  social:    
    - icon: "fontawesome/solid/rss"
      link: "https://geotribu.fr/feed_rss_created.xml"
      name: "S'abonner aux nouveaux contenus via RSS"
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/vienne-condrieu-agglomeration/"
      name: "L'organisation Github du service SIG de Vienne Condrieu Agglomération"
    - icon: fontawesome/brands/mastodon 
      link: https://mapstodon.space/@allfab
      name: "Allfab sur Mapstodon"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/search/results/all/?keywords=vienne%20condrieu%20agglomeration"
      name: "Les contenus de Vienne Condrieu Agglomération sur LinkedIn"
    - icon: "fontawesome/brands/youtube"
      link: https://www.youtube.com/@viennecondrieuagglomeratio8501
      name: "Chaîne Youtube de Vienne Condrieu Agglomération"
    - icon: "fontawesome/brands/facebook"
      link: "https://www.facebook.com/VienneCondrieuAgglomeration"
      name: "Page Facebook de Vienne Condrieu Agglomération"
    - icon: fontawesome/solid/paper-plane
      link: mailto:<igeo@vienne-condrieu-aggloemration.fr>
      name: "Nous contacter"
  # Cookie consent
  consent:
    title: Consentement 🍪
    actions:
      - accept
      - reject
    description: >- 
      Nous utilisons des cookies pour reconnaître vos visites et préférences répétées,
      ainsi que pour mesurer l'efficacité de notre documentation et si les utilisateurs
      trouvent ce qu'ils recherchent. Avec votre consentement, vous nous aidez
      à améliorer notre documentation.
      
# extra_css:
#   - assets/stylesheets/extra.css
#   - assets/stylesheets/home.css

# PLUGINS
plugins:
  - search:
      lang: fr
  - autolinks
  - awesome-pages  
  - glightbox
  - mermaid2
  - tags:
      tags_file: tags.md
  # - minify:
  #     minify_css: true
  #     css_files:
  #       - assets/stylesheets/extra.css
  #       - assets/stylesheets/home.css

# EXTENSIONS POUR AMÉLIORER markdown - https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - abbr
  # Admonition - https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - attr_list
  # Footnotes - https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  - md_in_html
  # Metadata - https://squidfunk.github.io/mkdocs-material/extensions/metadata
  - meta
  # PyMdown extensions - https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.saneheaders
  # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  # - pymdownx.snippets:
  #     auto_append: [content/toc_nav_ignored/snippets/glossaire.md]
  #     base_path:
  #       - "."
  #     check_paths: true
  #     url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # Permalinks - https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - toc:
      permalink: "#"
