name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
        uses: actions/checkout@v4
      
      - name: Installing a version of Python and (by default) adding it to the PATH
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Set cache_id variable and store to GITHUB_ENV environment variable
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      
      # https://github.com/actions/cache
      - name: Caching dependencies and build outputs to improve workflow execution time
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Python dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-minify-plugin
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-glightbox
          pip install mkdocs-open-in-new-tab
          pip install mkdocs-autolinks-plugin
        
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force